/**
 * `foundation.json` → Tailwind's own theme.
 *
 * This file is the bridge whose absence broke the whole colour story. The rules
 * hand every agent the brand scale and say "style from these tokens", agents do
 * the Tailwind-idiomatic thing and write `text-brand-950` — and Tailwind v4,
 * finding no `--color-brand-950` in any `@theme`, generates **no CSS**. The
 * class is inert, the page renders in inherited colours, and on a dark-seeded
 * project nobody can even see that the foundation was never applied.
 *
 * The fix is not a Caret-private colour scheme; it is defining Caret's tokens
 * into Tailwind's theme system, where a custom scale is exactly as first-class
 * as the stock palette. One scheme — Tailwind's — with `foundation.json` as its
 * source of truth:
 *
 *   @theme { --color-brand-950: #030303; }   →   text-brand-950 just works
 *
 * Written as its own file (`caret-theme.css`, imported by `global.css`) so a
 * token change can regenerate it alone and arrive as a CSS hot update instead
 * of a shell rebuild.
 */
import type { FoundationTokens } from "../types"

/** Kept in sync with the healer's ignore list — this file is Caret's, not content. */
export const THEME_CSS_FILENAME = "caret-theme.css"

/** `"Instrument Serif"` needs quoting in CSS; `Georgia, serif` must not get one pair around the lot. */
function cssFontFamily(family: string, fallback: string): string {
	const quoted = /[^a-zA-Z0-9-]/.test(family) ? `"${family}"` : family
	return `${quoted}, ${fallback}`
}

/** Google Fonts URL for the families the foundation names, weights the pages actually use. */
function fontImport(tokens: FoundationTokens): string {
	const families = [...new Set([tokens.typography.fontFamily, tokens.typography.displayFamily].filter(Boolean))] as string[]
	if (families.length === 0) return ""
	const query = families
		.map((family) => `family=${encodeURIComponent(family).replace(/%20/g, "+")}:wght@400;500;600;700;800;900`)
		.join("&")
	return `@import url("https://fonts.googleapis.com/css2?${query}&display=swap");\n`
}

/**
 * The generated theme. Colours and typography — the two axes agents style with
 * by *name* and therefore the two that were silently broken. Spacing and radius
 * ride on Tailwind's numeric utilities already and need no theme entries yet.
 */
export function foundationThemeCss(tokens: FoundationTokens): string {
	const lines: string[] = []

	for (const [step, value] of Object.entries(tokens.color.brand.scale ?? {})) {
		lines.push(`  --color-brand-${step}: ${value};`)
	}
	// The seed itself as the bare `brand` utility (`text-brand`, `bg-brand`) —
	// the scale may be empty on a hand-rolled foundation, the seed never is.
	if (tokens.color.brand.seed) lines.push(`  --color-brand: ${tokens.color.brand.seed};`)

	for (const [name, value] of Object.entries(tokens.color.semantic ?? {})) {
		lines.push(`  --color-${name}: ${value};`)
	}

	const body = cssFontFamily(tokens.typography.fontFamily, tokens.typography.fallback)
	const display = tokens.typography.displayFamily
		? cssFontFamily(tokens.typography.displayFamily, tokens.typography.displayFallback || tokens.typography.fallback)
		: body
	lines.push(`  --font-sans: ${body};`)
	lines.push(`  --font-display: ${display};`)

	return `/* GENERATED by Caret from tokens/foundation.json — do not edit; edit the foundation. */
${fontImport(tokens)}@theme {
${lines.join("\n")}
}

:root {
  --caret-font-family: ${body};
  --caret-font-display: ${display};
  --caret-font-base: ${tokens.typography.baseSize || 16}px;
}
`
}
